# RT-Thread building script for component

Import('rtconfig')
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Glob("*.c" )
print(cwd)
        
CPPPATH = [cwd]

CPPDEFINES = ['-DLUA2RTT_THREAD_STACK_SIZE=200000']

objs = DefineGroup('lua2rtt', src, depend = ['PKG_USING_ELUART'], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)


Return('objs')
