# RT-Thread building script for component

Import('rtconfig')
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Glob("*.c" )
print(cwd)
        
CPPPATH = [cwd]

CPPDEFINES = []

objs = DefineGroup('lua2rtt', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)


Return('objs')
