Import('rtconfig')
import os
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd]

SrcRemove(src, 'luac.c')

CPPDEFINES = []

#group = DefineGroup('lua-5.3.4', src, depend = ['PKG_USING_LUA', 'LUA_USING_PORTING_V534'], CPPPATH = CPPPATH)
group = DefineGroup('lua-5.3.4', src, depend = [''], CPPPATH = CPPPATH,CPPDEFINES=CPPDEFINES)

Return('group')
