Import('rtconfig')
import os
from building import *

cwd = GetCurrentDir()
src	= Glob('*.c')
CPPPATH = [cwd]

SrcRemove(src, 'luac.c')

CPPDEFINES = ["-DLUA_INT_TYPE_FALLBACK=LUA_INT_INT","-DLUA_FLOAT_TYPE_FALLBACK=LUA_FLOAT_DOUBLE"]

#group = DefineGroup('lua-5.3.4', src, depend = ['PKG_USING_LUA', 'LUA_USING_PORTING_V534'], CPPPATH = CPPPATH)
group = DefineGroup('lua-5.3.4', src, depend = ['PKG_USING_ELUART'], CPPPATH = CPPPATH,CPPDEFINES=CPPDEFINES)

Return('group')
