# RT-Thread building script for component

Import('rtconfig')
Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = Glob("*.c" )
print(cwd)
        
CPPPATH = [cwd]

CPPDEFINES = []

objs = DefineGroup('eluart', src, depend = ['PKG_USING_ELUART'], CPPPATH = CPPPATH, CPPDEFINES=CPPDEFINES)

#objs = objs + SConscript()


Return('objs')
